fix page style
crypto-pepe/pepe.blank pull request #5
Opened 2022-06-03 13:18 UTC by turbo-stump

2022-06-08 14:57 UTC, stuffy-idler commented on js/main.js
> +  const digits = score.toString().split("");
nit: can be written in FP-style as:
```typescript
score.toString().split("").forEach(digit => {
  currentScoreImageElement.src = `../img/assets/font_small_${digit}.png`;
  currentScoreImageElement.alt = `${digit}`;
  currentScoreElement.append(currentScoreImageElement);
});
```

2022-06-08 14:57 UTC, stuffy-idler commented on js/main.js
> +  medalElementChild.forEach((child) => medalElement.removeChild(child));
nit: can be rewritten as `medalElementChild.forEach(medalElement.removeChild)`

2022-06-08 14:58 UTC, stuffy-idler requested changes

2022-06-08 14:58 UTC, stuffy-idler commented on index.html
> +</html>
Missing EOF

2022-06-08 19:56 UTC, turbo-stump commented on js/main.js
> +  const digits = score.toString().split("");
done

2022-06-08 20:00 UTC, turbo-stump commented on js/main.js
> +  const digits = score.toString().split("");
done

2022-06-08 20:16 UTC, turbo-stump commented on js/main.js
> +  medalElementChild.forEach((child) => medalElement.removeChild(child));
done

2022-06-08 20:22 UTC, turbo-stump commented on js/main.js
> +  const digits = score.toString().split("");
done

2022-06-08 20:24 UTC, turbo-stump commented on index.html
> +</html>
done

2022-06-09 07:35 UTC, stuffy-idler commented on js/main.js
> +  currentScoreElementChild.forEach((child) =>
Leads to Illegal invocation

2022-06-09 07:35 UTC, stuffy-idler approved these changes

2022-06-09 08:19 UTC, stupid-boar approved these changes

2022-06-09 08:22 UTC, merged